services:
  redis:
    image: redis:latest
    container_name: rediska
    ports:
      - 6379:6379
    networks:
      - redis-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    depends_on:
      - redis
    ports:
      - 5540:5540
    volumes:
      - redis-insight:/data
    networks:
      - redis-net

volumes:
  redis-insight:

networks:
  redis-net:
    driver: bridge
