services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mydb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
      - redis
    networks:
      - redis-net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydb
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - redis-net

  redis:
    image: redis:latest
    container_name: rediska
    ports:
      - 6379:6379
    networks:
      - redis-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    depends_on:
      - redis
    ports:
      - 5540:5540
    volumes:
      - redis-insight:/data
    networks:
      - redis-net

volumes:
  postgres-data:
  redis-insight:

networks:
  redis-net:
    driver: bridge
